'use client'
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import 'bootstrap/dist/css/bootstrap.css';
import BootstrapClient from '@/components/BootstrapClient.js';
require('bootstrap/dist/js/bootstrap.bundle.min.js');
import { useEffect } from "react";
const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <html lang="en">
        <Providers>
          <body className={inter.className}>{children} </body>
        </Providers>
    </html>
  );
}
